---

version: "3.6"
services:

  caddy:
    build:
      target: development_build
      context: .
      dockerfile: ./docker/Dockerfile
    restart: unless-stopped
    volumes:
      - ./docker/caddy/certs:/root/.caddy  # saving certificates
      - ./docker/caddy/Caddyfile:/etc/Caddyfile:ro  # configuration
    ports:
      - "80:80"
      - "443:443"
