---

version: "3.7"
services:

  flask:
    restart: unless-stopped
    <<: &web
      build:
        context: .
        dockerfile: ./Dockerfile
        args:
          FLASK_ENV: development
      # volumes:
      #   - .:/code
        