name: Development build

on:
  push:
    branches:
      - develop
      - feature/docker
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    variables:
      REGISTRY_URL: docker.pkg.github.com/damienallen/mothership/website_flask
      TAG: latest

    steps:

    - uses: actions/checkout@v2
    - name: Checkout repo with submodules
      shell: bash
      run: |
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1

    - name: Build docker container
      run: |
        docker login docker.pkg.github.com --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }}
        docker pull $REGISTRY_URL:$TAG || true
        docker build -t $REGISTRY_URL:$TAG
          --cache-from $REGISTRY_URL:$TAG
          --build-arg DJANGO_ENV=production
          --target production_build
          -f docker/flask/Dockerfile .
        - docker push $REGISTRY_URL:$TAG

    env:
        CI: true